# Blog info
blog_name: Don
slogan: 明者自知，毅者自远
# url: http://www.forsigner.com

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
# keywords: forsigner,前端,设计,Hexo主题,前端开发,用户体验,设计,frontend,design,nodejs,JavaScript

home_nav:
  - name: Blog
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: Photography
    url: /photo/
    target_blank: false
  - name: Record
    url: /record/
    target_blank: false
  - name: Github
    url: https://github.com/zqh-wz
    target_blank: true # 在新页面打开

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false
  - name: 分类
    url: /category/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

toolbox:
  isShow: true # true|fase
  text: 目录

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  post: true
  about: false

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  open_in_new_window: false
  show_prev_next: false

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "THU-CST 九字班。"
  - type: mail
    icon: icon-mail
    text_key: email
    text_value: "zhang-qh19@mails.tsinghua.edu.cn"
  - type: location
    icon: icon-location
    text_value: Wenzhou, Zhejiang
